
version: 0.2
phases:
 install:
   commands:
     - echo Installing composer dependencies...
     - composer install
     - echo Installing npm packages...
     - npm install

 build:
   commands:
     - echo Build started on `date`
     - npm run build
     - echo Migrating database...
     - php artisan migrate --force

 post_build:
   commands:
     - echo Build completed on `date`
